apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-consumer-service
spec:
  selector:
    app: rabbitmq-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5672
  type: ClusterIP
